title: Kelechi Nwankwoala
logo: /assets/logo.JPG
description: >- # this means to ignore newlines until "baseurl:"
  Projects & musings of Kelechi Nwankwoala 
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.kelechin.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Maxwells-Angel

# Build settings
theme: minimal-mistakes-jekyll #minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
